# conditional mhagan
python run.py \
--training_ae 1 \
--exp_name ae \
--root_path ./data/iTransformer_datasets/ETT-small/ \
--data_path ETTh2.csv \
--ae_model_id ae_20240927 \
--ae_model iTransformer \
--d_model 64 \
--d_ff 256 \
--vari_masked_ratio 0.0 \
--mask_ratio 0.0 \
--data ETTh2 \
--features M \
--seq_len 192 \
--pred_len 192 \
--e_layers 2 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des etth2 \
--ae_batch_size 32 \
--train_epochs 10 \
--learning_rate 0.001 \
--use_norm 0 \
--gan_model ConditionalSAGAN \
--gan_model_id conditional_mhagan \
--self_attn \
--gan_batch_size 1024 \
--gen_lr 0.0001 \
--disc_lr 0.0001 \
--d_update 10 \
--use_hidden \
--gan_iter 40000 \
--load_iter 20000

python run.py \
--training_ae 0 \
--training_gan 1 \
--exp_name gan \
--root_path ./data/iTransformer_datasets/ETT-small/ \
--data_path ETTh2.csv \
--ae_model_id ae_20240927 \
--ae_model iTransformer \
--d_model 64 \
--d_ff 256 \
--vari_masked_ratio 0.0 \
--mask_ratio 0.0 \
--data ETTh2 \
--features M \
--seq_len 192 \
--pred_len 192 \
--e_layers 2 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des etth2 \
--ae_batch_size 32 \
--train_epochs 10 \
--learning_rate 0.001 \
--use_norm 0 \
--gan_model ConditionalSAGAN \
--gan_model_id conditional_mhagan \
--self_attn \
--gan_batch_size 1024 \
--gen_lr 0.0001 \
--disc_lr 0.0001 \
--d_update 10 \
--use_hidden \
--gan_iter 40000 \
--load_iter 40000



python run.py \
--training_ae 1 \
--exp_name ae \
--root_path ./data/iTransformer_datasets/ETT-small/ \
--data_path ETTh2.csv \
--ae_model_id ae_20240927 \
--ae_model iTransformer \
--d_model 128 \
--d_ff 512 \
--vari_masked_ratio 0.0 \
--mask_ratio 0.0 \
--data ETTh2 \
--features M \
--seq_len 288 \
--pred_len 288 \
--e_layers 2 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des etth2 \
--ae_batch_size 32 \
--train_epochs 10 \
--learning_rate 0.001 \
--use_norm 0 \
--gan_model ConditionalSAGAN \
--gan_model_id conditional_mhagan \
--self_attn \
--gan_batch_size 1024 \
--gen_lr 0.0001 \
--disc_lr 0.0001 \
--d_update 10 \
--use_hidden \
--gan_iter 40000 \
--load_iter 20000


python run.py \
--training_ae 0 \
--training_gan 1 \
--exp_name gan \
--root_path ./data/iTransformer_datasets/ETT-small/ \
--data_path ETTh2.csv \
--ae_model_id ae_20240927 \
--ae_model iTransformer \
--d_model 128 \
--d_ff 512 \
--vari_masked_ratio 0.0 \
--mask_ratio 0.0 \
--data ETTh2 \
--features M \
--seq_len 288 \
--pred_len 288 \
--e_layers 2 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des etth2 \
--ae_batch_size 32 \
--train_epochs 10 \
--learning_rate 0.001 \
--use_norm 0 \
--gan_model ConditionalSAGAN \
--gan_model_id conditional_mhagan \
--self_attn \
--gan_batch_size 1024 \
--gen_lr 0.0001 \
--disc_lr 0.0001 \
--d_update 10 \
--use_hidden \
--gan_iter 40000 \
--load_iter 40000


python run.py \
--training_ae 1 \
--exp_name ae \
--root_path ./data/iTransformer_datasets/ETT-small/ \
--data_path ETTh2.csv \
--ae_model_id ae_20240927 \
--ae_model iTransformer \
--d_model 128 \
--d_ff 512 \
--vari_masked_ratio 0.0 \
--mask_ratio 0.0 \
--data ETTh2 \
--features M \
--seq_len 432 \
--pred_len 432 \
--e_layers 2 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des etth2 \
--ae_batch_size 32 \
--train_epochs 10 \
--learning_rate 0.001 \
--use_norm 0 \
--gan_model ConditionalSAGAN \
--gan_model_id conditional_mhagan \
--self_attn \
--gan_batch_size 1024 \
--gen_lr 0.0001 \
--disc_lr 0.0001 \
--d_update 10 \
--use_hidden \
--gan_iter 40000 \
--load_iter 20000


python run.py \
--training_ae 0 \
--training_gan 1 \
--exp_name gan \
--root_path ./data/iTransformer_datasets/ETT-small/ \
--data_path ETTh2.csv \
--ae_model_id ae_20240927 \
--ae_model iTransformer \
--d_model 128 \
--d_ff 512 \
--vari_masked_ratio 0.0 \
--mask_ratio 0.0 \
--data ETTh2 \
--features M \
--seq_len 432 \
--pred_len 432 \
--e_layers 2 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des etth2 \
--ae_batch_size 32 \
--train_epochs 10 \
--learning_rate 0.001 \
--use_norm 0 \
--gan_model ConditionalSAGAN \
--gan_model_id conditional_mhagan \
--self_attn \
--gan_batch_size 1024 \
--gen_lr 0.0001 \
--disc_lr 0.0001 \
--d_update 10 \
--use_hidden \
--gan_iter 40000 \
--load_iter 40000


python run.py \
--training_ae 1 \
--exp_name ae \
--root_path ./data/iTransformer_datasets/ETT-small/ \
--data_path ETTh2.csv \
--ae_model_id ae_20240927 \
--ae_model iTransformer \
--d_model 128 \
--d_ff 512 \
--vari_masked_ratio 0.0 \
--mask_ratio 0.0 \
--data ETTh2 \
--features M \
--seq_len 816 \
--pred_len 816 \
--e_layers 2 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des etth2 \
--ae_batch_size 32 \
--train_epochs 10 \
--learning_rate 0.001 \
--use_norm 0 \
--gan_model ConditionalSAGAN \
--gan_model_id conditional_mhagan \
--self_attn \
--gan_batch_size 1024 \
--gen_lr 0.0001 \
--disc_lr 0.0001 \
--d_update 10 \
--use_hidden \
--gan_iter 40000 \
--load_iter 20000


python run.py \
--training_ae 0 \
--training_gan 1 \
--exp_name gan \
--root_path ./data/iTransformer_datasets/ETT-small/ \
--data_path ETTh2.csv \
--ae_model_id ae_20240927 \
--ae_model iTransformer \
--d_model 128 \
--d_ff 512 \
--vari_masked_ratio 0.0 \
--mask_ratio 0.0 \
--data ETTh2 \
--features M \
--seq_len 816 \
--pred_len 816 \
--e_layers 2 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des etth2 \
--ae_batch_size 32 \
--train_epochs 10 \
--learning_rate 0.001 \
--use_norm 0 \
--gan_model ConditionalSAGAN \
--gan_model_id conditional_mhagan \
--self_attn \
--gan_batch_size 1024 \
--gen_lr 0.0001 \
--disc_lr 0.0001 \
--d_update 10 \
--use_hidden \
--gan_iter 40000 \
--load_iter 40000