# ECl
python run_ae.py \
--is_ae_training 1 \
--root_path ./data/iTransformer_datasets/electricity/ \
--data_path electricity.csv \
--model_id exp_multi_lr0001_bsz32 \
--model iTransformer \
--d_model 128 \
--data custom \
--features M \
--seq_len 432 \
--pred_len 288 \
--e_layers 2 \
--enc_in 321 \
--dec_in 321 \
--c_out 321 \
--des ecl \
--ae_batch_size 32 \
--train_epochs 100 \
--patience 10 \
--learning_rate 0.001

python run_ae.py \
--is_ae_training 0 \
--root_path ./data/iTransformer_datasets/electricity/ \
--data_path electricity.csv \
--model_id exp_multi_lr0001_bsz32 \
--model iTransformer \
--d_model 128 \
--data custom \
--features M \
--seq_len 432 \
--pred_len 288 \
--e_layers 2 \
--enc_in 321 \
--dec_in 321 \
--c_out 321 \
--des ecl \
--ae_batch_size 32 \
--train_epochs 100 \
--patience 10 \
--learning_rate 0.001